# Generated by Django 6.0.2 on 2026-03-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_about'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Login1',
        ),
    ]
