# Generated by Django 6.0.2 on 2026-03-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_login_login1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login1',
            new_name='SignUp',
        ),
    ]
