# Generated by Django 6.0.2 on 2026-03-07 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_login1_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='passw',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='user',
        ),
    ]
