# Generated by Django 6.0.2 on 2026-03-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_test_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='created',
            field=models.DateTimeField(null=True),
        ),
    ]
